openapi: 3.0.0
info:
  title: Renewal Service
  description: "This service is used for loan renewal. The process of renewal consist of either extending the repayment period of an existing loan and replacing it with different terms, often used to manage cash flow, adjust to new financial circumstances, or develop a banking relationship."
  contact:
    name: ESF_APServicesDesignTeam
    email: DL-NA-ESF_APServicesDesignTeam@fiserv.com
  version: 11.0.0
servers:
- url: https://virtserver.swaggerhub.com/Bank_Sol_Org/RenewalService/11.0.0
  description: SwaggerHub API Auto Mocking
- url: /
paths:
  /accounts/renewal:
    post:
      tags:
      - Adds a Loan Renewal
      summary: Renews a Loan Account
      operationId: postRenewalLoan
      parameters:
      - name: EFXHeader
        in: header
        description: The message header request aggregate contains common information for all request messages
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/EFXHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RenewalAddRqType"
            examples:
              RenewalAddRq:
                $ref: "#/components/examples/RenewalAddRq"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RenewalAddRsType"
              examples:
                RenewalAddRs_Success:
                  $ref: "#/components/examples/RenewalAddRs_Success"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RenewalAddRsType"
              examples:
                RenewalAddRs_BadRequest:
                  $ref: "#/components/examples/RenewalAddRs_BadRequest"
        default:
          description: See HTTP Status Code Standards
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RenewalAddRsType"
components:
  schemas:
    AdvanceOptionType:
      title: AdvanceOptionType
      type: string
      description: Indicates whether the recurring charge is advanced and to which balance the advanced charge applies
      enum:
      - FeeAdvance
      - PrincipalAdvance
      - None
    CRADataType:
      title: CRADataType
      type: object
      properties:
        CRALoanType:
          type: string
          description: "CRA Loan Type. Valid values are None, SmallBusiness, SmallFarm, OtherLineLoanOtherSmallBusiness, HomeEquity, CreditCard, MotorVehicle,  OtherSecuredConsumerLoan, OtherUnsecuredConsumerLoan, OtherLoanData,"
        CRANewFunds:
          type: number
          description: CRA new funds amount.
      description: Community Reinvestment Act Data.
    CurAmtType:
      title: CurAmtType
      type: object
      properties:
        Amt:
          type: number
          description: Amount.
    SvcIdentType:
      title: SvcIdentType
      type: object
      properties:
        SvcProviderName:
          maxLength: 1024
          type: string
          description: Service Provider Name is a globally unique identifier for a service provider which indicates the location of the Service Provider that gave the error.
        SvcNbr:
          maxLength: 36
          type: string
          description: Service Number.
        SvcName:
          maxLength: 32
          type: string
          description: Service Name.
    RelationshipRoleType:
      title: RelationshipRoleType
      type: string
      enum:
      - Officer
      - SecondOfficer
      - ThirdOfficer
      - FourthOfficer
      - ReferralOfficer
    RelationshipMgrType:
      title: RelationshipMgrType
      required:
      - RelationshipMgrIdent
      type: object
      properties:
        RelationshipMgrIdent:
          maxLength: 36
          type: string
          description: Relationship Manager Identifier. Identifies officer/employee of financial institution.
        RelationshipRole:
          $ref: "#/components/schemas/RelationshipRoleType"
    RenewalKeysType:
      title: RenewalKeysType
      required:
      - AcctKeys
      type: object
      properties:
        AcctKeys:
          $ref: "#/components/schemas/AcctKeysType"
        RenewalDt:
          type: string
          description: Renewal Date.
          format: date
    AcctKeysType:
      title: AcctKeysType
      required:
      - AcctId
      type: object
      properties:
        AcctId:
          maxLength: 36
          type: string
          description: Account Identifier. Uniquely identifies an account held at a financial institution.
        SubAcctId:
          maxLength: 36
          type: string
          description: Sub Account Identifier.
        AcctType:
          maxLength: 80
          type: string
          description: "Account Type. Classifies the type of product with which an account is associated. This element is required when adding a new account and by using this value we can identify if the account is a savings, a checking, a time deposit, loan account, etc."
        FIIdentType:
          type: array
          description: Financial Institution Identification Type.
          items:
            maxLength: 80
            type: string
        FIIdent:
          maxLength: 34
          type: array
          description: Financial Institution Identification.
          items:
            maxLength: 34
            type: string
    ReportablePointsAmtType:
      title: ReportablePointsAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    MaxCreditLimitAmtType:
      title: MaxCreditLimitAmtType
      description: Maximum credit limit amount
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    IntRateDataType:
      title: IntRateDataType
      type: object
      properties:
        BasedOnCode:
          maxLength: 80
          type: string
          description: "Based On Code.Source of interest rate which can be used alone or with additional factors that, when combined, calculate an interest rate."
        AccrualMethod:
          maxLength: 80
          type: string
          description: "Accrual Method. Valid values are: PrincipalAndInterest, PrincipalPlusInterest, Amortized, Rule78th, NegativeAmortization, Simple, AddOn."
        DailyAccrual:
          type: string
          description: "Daily Accrual. Indicates how 'daily' is determined when interest is accrued on a daily basis. Valid values: Actual360 and Actual365.\""
        MinimumInterest:
          type: number
          description: Minimum interest amount. For Loan Products this is the minimum amount that must be repaid to the account before a payoff may occurr.
    VarianceFactorTypeType:
      title: VarianceFactorTypeType
      type: string
      enum:
      - None
      - Variance
      - Factor
      - Factor+Variance
      - FactorPlusVariance
      - VarianceXFactor
      - FactorPlusAddtlFactor
      - VarianceXFactorXRate
      - VarianceXFactorPlusRate
    RateChangeDataType:
      title: RateChangeDataType
      type: object
      properties:
        VarianceFactorType:
          $ref: "#/components/schemas/VarianceFactorTypeType"
        RateFactor:
          type: number
          description: Rate Factor. Whole percentage of the related index rate used to calculate rate changes
        RateFactorTwo:
          type: number
          description: Additional rate factor two. Whole percentage of the related index rate used to calculate rate changes
        RateVariance:
          type: number
          description: Rate Variance. Percentage that the interest rate varies from its related index rate
        RateVarianceTwo:
          type: number
          description: Additional variance two percentage that the interest rate varies from its related index rate
    FeesFinancedAmtType:
      title: FeesFinancedAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    FeesPrepaidAmtType:
      title: FeesPrepaidAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    FeesChargedAmtType:
      title: FeesChargedAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    ExpensesFinancedAmtType:
      title: ExpensesFinancedAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    ExpensesChargedAmtType:
      title: ExpensesChargedAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    OriginationFeeType:
      title: OriginationFeeType
      required:
      - CurAmt
      type: object
      properties:
        FeeIdent:
          maxLength: 36
          type: string
          description: Fee Identification.
        Desc:
          maxLength: 200
          type: string
          description: Description.
        FeeOptionInd:
          type: boolean
          description: Fee Option Indicator. Indicates whether loan fees are financed with the loan or prepaid by the borrower at the beginning of the loan.
        AdvanceOption:
          $ref: "#/components/schemas/AdvanceOptionType"
        FeeDeferralInd:
          type: boolean
          description: Fee Deferral Indicator. Indicates whether loan fees are deferred.
        FeeReportableInd:
          type: boolean
          description: Fee Reportable Indicator. Indicates whether loan fees are added to the reportable points.
        FeeAPRCalcInd:
          type: boolean
          description: Fee APR Indicator. Indicates whether loan fees are included in the APR calculation.
        CurAmt:
          $ref: "#/components/schemas/CurAmtType"
    RecurModelType:
      title: RecurModelType
      type: object
      properties:
        RecurRule:
          type: array
          description: Recurrence Rule.
          items:
            $ref: "#/components/schemas/RecurRuleType"
    RecurRuleType:
      title: RecurRuleType
      type: object
      properties:
        RecurType:
          type: string
          description: "Recurrence Type. Indicates the pattern of recurrence. Valid values are None, Monthly, Quarterly, SemiYearly, Yearly, Weekly, BiWeekly, BiMonthly, TwiceMonthly, Maturity."
        RecurStartDate:
          type: string
          description: Recurrence Start Date.
          format: date
        Occurrences:
          type: integer
          description: Occurrences.
          format: int64
    InterestBillingType:
      title: InterestBillingType
      type: object
      properties:
        RecurModel:
          $ref: "#/components/schemas/RecurModelType"
    BillingMethodType:
      title: BillingMethodType
      type: string
      enum:
      - None
      - BillingNotice
      - BillingByStmt
      - Coupon
      - DirectDebitDDA
      - DirectDebitSDA
      - DirectDebitDDAStmt
      - DirectDebitSDAStmt
      - ACHXferDDA
      - ACHXferSDA
      - ACHXferDDAStmt
      - ACHXferSDAStmt
    FromAcctKeysType:
      title: FromAcctKeysType
      allOf:
      - $ref: "#/components/schemas/AcctKeysType"
      - type: object
    LoanBillingType:
      title: LoanBillingType
      type: object
      properties:
        BillingMethod:
          $ref: "#/components/schemas/BillingMethodType"
        CouponOrderStatus:
          type: string
          description: Coupon Order Status.
          enum:
          - DoNotOrder
          - OrderNow
          - OrderInProgress
        FromAcctKeys:
          $ref: "#/components/schemas/FromAcctKeysType"
        ACHPayerId:
          maxLength: 36
          type: string
          description: ACH Payer Identifier.
        Desc:
          maxLength: 200
          type: string
          description: Description.
    EscrowAmtType:
      title: EscrowAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    OtherEscrowAmtType:
      title: OtherEscrowAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    PmtSchedType:
      title: PmtSchedType
      type: object
      properties:
        RecurModel:
          $ref: "#/components/schemas/RecurModelType"
        NumberOfTimes:
          type: integer
          description: Number of Times. Number of times the schedule plan must repeat.
          format: int64
        CurAmt:
          $ref: "#/components/schemas/CurAmtType"
        BalPercent:
          type: number
          description: Balance Percent.
        EscrowAmt:
          $ref: "#/components/schemas/EscrowAmtType"
        OtherEscrowAmt:
          $ref: "#/components/schemas/OtherEscrowAmtType"
    MortgagePointsYTDAmtType:
      title: MortgagePointsYTDAmtType
      allOf:
      - $ref: "#/components/schemas/CurAmtType"
      - type: object
    RenewalAddRqType:
      title: RenewalAddRqType
      type: object
      properties:
        OvrdAutoAckInd:
          type: boolean
          description: Override AutoAcknowledge Indicator. Used when the midleware is in charge of  auto-acknowledgement of exceptions.
        OvrdExceptionData:
          $ref: "#/components/schemas/OvrdExceptionDataType"
        RenewalInfo:
          $ref: "#/components/schemas/RenewalInfoType"
    RenewalAddRsType:
      title: RenewalAddRsType
      required:
      - Status
      type: object
      properties:
        Status:
          $ref: "#/components/schemas/StatusType"
        RenewalStatusRec:
          $ref: "#/components/schemas/RenewalStatusRecType"
    RenewalInfoType:
      title: RenewalInfoType
      type: object
      properties:
        AcctKeys:
          $ref: "#/components/schemas/AcctKeysType"
        RenewalDt:
          type: string
          description: Renewal Date.
          format: date
        ClassCode:
          maxLength: 80
          type: string
          description: Class Code. Used to group accounts. The Class Code controls the method of processing and reporting accounts.
        RelationshipMgr:
          type: array
          description: Relationship Manager. Stores information about the FI officers that have management responsibility of the Account .
          items:
            $ref: "#/components/schemas/RelationshipMgrType"
        ReportPurposeCode:
          maxLength: 80
          type: string
          description: Report Purpose Code. Use for Call reporting.
        CancelPremiumInsurance:
          type: boolean
          description: Cancel Premium Insurance
        CRAData:
          $ref: "#/components/schemas/CRADataType"
        InterestBilling:
          $ref: "#/components/schemas/InterestBillingType"
        RevolvingLoanCode:
          type: string
          description: "Revolving Loan Code. Valid values are: SingleAdvance, CreditLimit and AdvanceLimit."
        MaxCreditLimitAmt:
          $ref: "#/components/schemas/MaxCreditLimitAmtType"
        LoanBilling:
          $ref: "#/components/schemas/LoanBillingType"
        IntRateData:
          $ref: "#/components/schemas/IntRateDataType"
        RateChangeData:
          $ref: "#/components/schemas/RateChangeDataType"
        Rate:
          type: number
          description: Rate.
        MortgagePointsYTDAmt:
          $ref: "#/components/schemas/MortgagePointsYTDAmtType"
        OriginationFee:
          type: array
          description: Fee.
          items:
            $ref: "#/components/schemas/OriginationFeeType"
        ExpensesFinancedAmt:
          $ref: "#/components/schemas/ExpensesFinancedAmtType"
        FeesFinancedAmt:
          $ref: "#/components/schemas/FeesFinancedAmtType"
        FeesPrepaidAmt:
          $ref: "#/components/schemas/FeesPrepaidAmtType"
        ExpensesChargedAmt:
          $ref: "#/components/schemas/ExpensesChargedAmtType"
        FeesChargedAmt:
          $ref: "#/components/schemas/FeesChargedAmtType"
        ReportablePointsAmt:
          $ref: "#/components/schemas/ReportablePointsAmtType"
        PmtSched:
          type: array
          description: Payment Schedule.
          items:
            $ref: "#/components/schemas/PmtSchedType"
    RenewalStatusType:
      title: RenewalStatusType
      required:
      - RenewalStatusCode
      type: object
      properties:
        RenewalStatusCode:
          maxLength: 80
          type: string
          description: Renewal Status Code.
          enum:
          - Valid
        EffDt:
          pattern: "[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\\.[0-9]{3})?((-|\\+)[0-9]{2}:[0-9]{2})?)?)?"
          type: string
          description: Effective Date. The date that an associated action takes effect.
    RenewalStatusRecType:
      title: RenewalStatusRecType
      required:
      - RenewalKeys
      - RenewalStatusType
      type: object
      properties:
        SvcIdent:
          $ref: "#/components/schemas/SvcIdentType"
        RenewalKeys:
          $ref: "#/components/schemas/RenewalKeysType"
        RenewalStatus:
          $ref: "#/components/schemas/RenewalStatusType"
    EFXHeader:
      required:
      - OrganizationId
      type: string
      properties:
        OrganizationId:
          maxLength: 36
          type: string
          description: "Organization identifier is a unique identifier that represents the financial institution or holding company.  This identifier does not necessarily match the organization identifier or bank identifier in the backend system. To ensure uniqueness across all institutions in all parts of the world, use the Dun & Bradstreet number."
        TrnId:
          maxLength: 36
          type: string
          description: Transaction UUID (Universal Unique Identifier) of the current message.
        VendorId:
          maxLength: 255
          type: string
          description: 'Unique vendor identification number provided by Fiserv to identify the vendor. '
        MultiSystemInd:
          type: boolean
          description: For internal use only. Indicates Multi-System environment is enabled.
        SvcNbr:
          maxLength: 36
          type: string
          description: For organizations processing the Multi-System environment this identifies the Service Provider (account processor).
        Context:
          $ref: "#/components/schemas/Context"
      example: "{ \"TrnId\": \"622182\", \"OrganizationId\": \"PRMOrg10\", \"VendorId\": \"112233\", \"Context\":{ \"Channel\": \"WEB\" } }"
    Context:
      type: object
      properties:
        ClientAppName:
          maxLength: 40
          type: string
          description: "Name of the client application that is used to send the service request, such as Architect, Commercial Center and others."
        Channel:
          maxLength: 80
          type: string
          description: "Name of the channel used by the client application.\n  - 'Online'\n  - 'Phone' \n  - 'Branch'\n  - 'EFT'\n  - 'Teller'\n  "
        ClientDateTime:
          pattern: "[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\\.[0-9]{3})?((-|\\+)[0-9]{2}:[0-9]{2})?)?)?"
          type: string
          description: Client date and time as reported by the client application that is making the service request.
        isOverridden:
          type: boolean
          description: Indicates whether previous exception is being overridden by the sender.
        TrnIdent:
          maxLength: 36
          type: string
          description: "Unique identification value of transaction defined by the client.  Also known as Trace Number or Sequence in some systems. When used by a Network defined transaction,  the value of this identifier is typically set to narrow character of 12."
        ClientTerminalSeqNum:
          maxLength: 36
          description: "Client terminal sequence number. type: string"
        OriginatorType:
          type: integer
          description: "The type of organization that the originator represents. This is usually a coded value representing the industry that the organization operates in. It contains the SIC code. For ISO 8583 (DE18) the element is restricted to narrow character of maximum length of 4.  Originator Type codes that apply to financial institutions are:\n  6010 - Financial institution—bank, savings and loan (S and L), or credit union  \n  6011 - Financial institution—ATM \n  6012 - Financial institution—merchandise sale \n  6999 - Financial institution—home banking"
          format: int64
        TerminalIdent:
          maxLength: 36
          type: string
          description: Unique code identifying a terminal at the card acceptor location (such as terminal code or terminal number of ATM). See For ISO 8583 (DE41) the element is restricted to a narrow character with maximum length of 8.
        TerminalAddr1:
          maxLength: 64
          type: string
          description: Terminal address line 1.
        TerminalAddr2:
          maxLength: 64
          type: string
          description: Terminal address line 2.
        TerminalAddr3:
          maxLength: 64
          type: string
          description: Terminal address line 3.
        TerminalAddr4:
          maxLength: 64
          type: string
          description: Terminal address line 4.
        TerminalCity:
          maxLength: 40
          type: string
          description: Terminal city name.
        TerminalCounty:
          maxLength: 40
          type: string
          description: Terminal county name.
        TerminalStateProv:
          maxLength: 32
          type: string
          description: State province value as per ISO 3166-2:US codes where the terminal is located.
        TerminalPostalCode:
          maxLength: 11
          type: string
          description: 'Postal Code where the terminal is located. '
        TerminalCountryCodeSource:
          $ref: "#/components/schemas/CountryCodeSourceType"
        TerminalCountryCodeValue:
          maxLength: 80
          type: string
          description: Country code value as per the ISO source code set in the TerminalCountryCodeSource field.
        PhoneType:
          maxLength: 80
          type: string
          description: "Type of a phone. Valid values are: - 'EvePhone' - 'DayPhone' - 'EveFax' - 'DayFax' - 'Home' - 'Work' - 'Mobile' - 'Fax' - 'Pager' - 'Modem' - 'Other'"
        PhoneNum:
          type: string
          description: Phone number.
        PhoneExchange:
          maxLength: 80
          type: string
          description: Phone exchange.
        TerminalOwnerName:
          maxLength: 40
          type: string
          description: Name of the owner or operator of the terminal.  For ISO 8583 (DE43) the element is restricted to C-15.
        SystTraceAuditNum:
          maxLength: 36
          type: string
          description: Number assigned by the transaction originator to assist in identifying a transaction uniquely. The trace number remains unchanged for all messages throughout the life of a transaction. This number is not a terminal receipt number. The originating processor increments the trace number by one for each transaction sent to the switch. For ISO 8583 (DE11) the element is restricted to NC-6
        NetworkIdent:
          maxLength: 80
          type: string
          description: Identifies the interchange network for the transaction. The transaction is applied to the specified network settlement counts and balances. For ISO 8583 (DE62) the element is restricted to NC-6
        NetworkRefIdent:
          maxLength: 36
          type: string
          description: Document reference supplied by the system retaining the original source document and used to assist in locating that document. The acquirer of a transaction assigns this number. The issuer processor must retain it in the event that a chargeback is submitted for the transaction. For ISO 8583 (DE37) the element is restricted to C-12.
        AcquirerIdent:
          maxLength: 36
          type: string
          description: Identifier of the acquirer who processes the financial transaction. It is a mandatory element in all authorization and financial messages and does not change throughout the life of a transaction. EPOC considers the acquirer as the terminal owner for reporting purposes. For ISO 8583 (DE32) the element is restricted to C-12
        AcquirerCountryCodeSource:
          $ref: "#/components/schemas/CountryCodeSourceType"
        AcquirerCountryCodeValue:
          maxLength: 80
          type: string
          description: Country code value of Acquirer as per the ISO source code set in the AcquirerCountryCodeSource field.
        MerchNum:
          maxLength: 23
          type: string
          description: Unique identification number of a merchant.  For ISO 8583 (DE42) the element is restricted to C-15
        SettlementDate:
          type: string
          description: Transaction settlement date. Used by ISO 8583 (DE63).
          format: date
        SettlementIdent:
          maxLength: 36
          type: string
          description: Identification of the settlement account in which the transaction will be settled.
        BusinessApplIdent:
          maxLength: 80
          type: string
          description: |-
            Identification of the business application. Valid values are:
              - 'P2P' - Person-to-Person
              - 'C2B' - Consumer-to-Business
              - 'A2A' - Account-to-Account
              - 'B2C' - Business-to-Consumer
              - 'B2B' - Business-to-Business
              - 'G2C' - Government-to-Consumer
              - 'C2G' - Consumer-to-Government
        BranchIdent:
          maxLength: 22
          type: string
          description: Branch identification number.
        TellerIdent:
          maxLength: 80
          type: string
          description: Teller identification number.
        TillIdent:
          maxLength: 80
          type: string
          description: Till identification number.
        AMPMCode:
          type: string
          description: 'Transaction posting code. '
          enum:
          - AM
          - PM
        ReentryType:
          type: string
          description: Type of re-entry.
          enum:
          - Manual
          - Auto
        GroupIdent:
          maxLength: 80
          type: string
          description: Transaction group identifier.
        TellerTrnData:
          $ref: "#/components/schemas/TellerTrnDataType"
        AdditionalSettings:
          type: object
          additionalProperties: true
          description: Contains additional information required to successfully process the transaction. Required By Cleartouch
    CountryCodeSourceType:
      title: CountryCodeSourceType
      type: string
      description: |-
        Country code value as per the ISO source code. Posible values:
          - 'ISO3166-Numeric'
          - 'ISO3166-Alpha-3'
      enum:
      - ISO3166Numeric
      - ISO3166Alpha3
      - ISO3166-Numeric
      - ISO3166-Alpha-3
    TellerTrnDataType:
      title: TellerTrnData
      type: object
      properties:
        TellerIdent:
          maxLength: 80
          type: string
          description: Teller identification number.
        TrnConductorData:
          type: array
          description: 'Contains data elements that identify the conductor of the  transaction at the teller line. '
          items:
            $ref: "#/components/schemas/TrnConductorDataType"
      description: Teller Transaction Data.
    TrnConductorDataType:
      title: TrnConductorType
      type: object
      properties:
        TrnConductorIdent:
          maxLength: 80
          type: string
          description: Identifies the person conducting the transaction.
        NoConductorReason:
          maxLength: 80
          type: string
          description: "No conductor reason is used when a conductor cannot be identified. Valid values are:\n  - 'ArmoredCarSvc '\n  - 'MailDeposit' \n  - 'NightDeposit' \n  - 'ATM' \n  - 'AggregatedTransaction' \n  - 'CourierSvc' "
      description: Transaction conductor data contains data elements that identify  the conductor of a transaction at the teller line.
    OvrdExceptionDataType:
      title: OvrdExceptionDataType
      type: object
      properties:
        OverrideException:
          type: array
          description: List of the exceptions that can be overridden.
          items:
            $ref: "#/components/schemas/OverrideExceptionType"
      description: Details of the exceptions that can be manually acknowledged by the client.
    OverrideExceptionType:
      title: OverrideExceptionType
      type: object
      properties:
        SubjectRole:
          type: string
          description: Role of the subject who is overriding the exception.
        SubjectIdent:
          maxLength: 36
          type: string
          description: Subject identification value to identify the subject who  is overriding the exception.
        OvrdExceptionCode:
          maxLength: 40
          type: string
          description: Override exception code to be overridden. This can be the  ServerStatusCode from the Message Status section.
        OvrdElement:
          $ref: "#/components/schemas/OvrdElementType"
    OvrdElementType:
      title: OvrdElementType
      type: object
      description: Information about the elements that corresponds to the override exception code.
      allOf:
      - $ref: "#/components/schemas/SubjectElementType"
      - type: object
    SubjectElementType:
      title: SubjectElementType
      type: object
      properties:
        Path:
          type: string
          description: "Path of the element (in XPath absolute notation format) where the error occurred.  If the error occurred at the top-level element, then name of the element is returned in the response. "
        ServerPath:
          maxLength: 256
          type: string
          description: "Server Path is the Service Provider’s identification of the field in their schema, such as an XPath, field ID, or field name that is associated with the ServerStatusCode. If this element is set, it must be returned in the ServerPath element of the OvrdExceptionData aggregate if the exception is being overridden."
        Value:
          maxLength: 256
          type: string
          description: "Human readable information of the EFX data value of the element to  be overridden. This value should not be provided for the fields that  cannot be represented as a string, for example, binary data."
      description: Information about the subject element.
    StatusType:
      title: StatusType
      required:
      - Severity
      - StatusCode
      - StatusDesc
      - SvcProviderName
      type: object
      properties:
        Id:
          type: string
          description: Status identification number.
        StatusCode:
          maxLength: 20
          type: string
          description: 'EFX Standard Status code that indicates the result of API response. '
        StatusDesc:
          maxLength: 255
          type: string
          description: 'Brief description about the EFX status code. '
        Severity:
          $ref: "#/components/schemas/SeverityType"
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              -  'Cleartouch'
              -  'DNA'
              -  'Precision'
              -  'Premier'
              -  'Signature'
              -  'Finxact'
              -  'NIA'
              -  'Director'
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Indicates whether the exception can be overridden by resubmitting the request message.
        SubjectRole:
          maxLength: 80
          type: string
          description: "Authorization level required to override, such as Teller and Supervisor."
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: "#/components/schemas/SubjectElementType"
        ContentHTML:
          type: string
          description: "Response status in HTML format. This parameter returns only in some  cases. #(excluding the core specific information), for example,  in Premier, upon failure an HTML page is provided to support the  maintenance of reported failures."
        AdditionalStatus:
          type: array
          description: 'Additional statuses of the response message. '
          items:
            $ref: "#/components/schemas/AdditionalStatusType"
      description: 'Details of the API response messages.            '
    SeverityType:
      title: SeverityType
      type: string
      description: 'Severity type of the EFX status code. '
      enum:
      - Error
      - Warning
      - Info
    AdditionalStatusType:
      title: AdditionalStatusType
      type: object
      properties:
        StatusCode:
          maxLength: 20
          type: string
          description: 'EFX Standard Status code that indicates the result of API response. '
        StatusDesc:
          maxLength: 255
          type: string
          description: Brief description about the EFX status code.
        Severity:
          $ref: "#/components/schemas/SeverityType"
        SvcProviderName:
          maxLength: 1024
          type: string
          description: |-
            Name of a service provider. Possible values are:
              - 'Cleartouch'
              - 'DNA'
              - 'Precision'
              - 'Premier'
              - 'Signature'
              - 'Finxact'
              - 'NIA'
              - 'Director'
        ServerStatusCode:
          maxLength: 20
          type: string
          description: 'Server status code of the service provider''s application.  '
        ServerStatusDesc:
          maxLength: 255
          type: string
          description: Description of the server status code of the service provider's application.
        OvrdExceptionInd:
          type: boolean
          description: Flag that indicates whether the exception can be overridden by resubmitting the request message.
        SubjectElement:
          type: array
          description: Information about the elements that caused the status.
          items:
            $ref: "#/components/schemas/SubjectElementType"
  examples:
    RenewalAddRq:
      value:
        RenewalInfo:
          AcctKeys:
            AcctId: 4007
            AcctType: LOAN
        RenewalDt: 2025-08-29
        ClassCode: 1
        RelationshipMgr:
        - RelationshipMgrIdent: 200
          RelationshipRole: Officer
        ReportPurposeCode: 23
        CancelPremiumInsurance: false
        CRAData:
          CRALoanType: HomeEquity
          CRANewFunds: 200000.0
        InterestBilling:
          RecurModel:
            RecurRule:
            - RecurType: Monthly
              RecurStartDate: 2025-09-29
        RevolvingLoanCode: AdvanceLimit
        MaxCreditLimitAmt:
          Amt: 300000.0
        LoanBilling:
          BillingMethod: Coupon
          CouponOrderStatus: OrderNow
        InterestRateData:
          BasedOnCode: 1
          AccrrualMethod: PrincipalAndInterest
          DailyAccrual: Actual365
          MinimumInterest: 1000
        RateChangeData:
          VarianceFactorType: Variance
          RateVariance: 1
        Rate: 7
        MortgagePointsYTDAmt:
          Amt: 100.0
        OriginationFee:
        - FeeIdent: 1
          CurAmt:
            Amt: 500.0
        - FeeIdent: 2
          CurAmt:
            Amt: 300.0
        PmtSched:
        - RecurModel:
            RecurRule:
            - RecurType: BiMonthly
            RecurStarDate: 2025-09-29
          NumberOfTimes: 12
          CurAmt:
            Amt: 100
    RenewalAddRs_BadRequest:
      value:
        Status:
          StatusCode: 1090
          StatusDesc: Invalid Value
          Severity: Error
          SvcProviderName: Provider
          SvcProviderCode: XXXX
          ServerStatusDesc: Amount cannot be negative
    RenewalAddRs_Success:
      value:
        Status:
          StatusCode: 0
          StatusDesc: Success
          Severity: Info
          SvcProviderName: Provider
        RenewalStatusRec:
          RenewalKeys:
            AcctKeys:
              AcctId: 4007
              AcctType: LOAN
            RenewalDt: 2025-08-29
          RenewalStatus:
            RenewalStatusCode: Valid
            EffDt: 2025-08-01T19:30:59.925+05:00
